### ISSUE TITLE
Python fault when it should be asking for password

### ISSUE THREAD

**Issue by SheamusPatt** [SheamusPatt/musicbrainz-isrcsubmit#1]
It works fine up until the point where it needs me to enter my password for MusicBrainz. At that point, I get a python exception.

Do you want to submit? [y/N] y

Traceback (most recent call last):
  File "/bigdata/DigitalDownloads/../src/musicbrainz-isrcsubmit/isrcDigitalSubmit.py", line 663, in <module>
    main(sys.argv)
  File "/bigdata/DigitalDownloads/../src/musicbrainz-isrcsubmit/isrcDigitalSubmit.py", line 652, in main
    ws2.submit_isrcs(tracks2isrcs)
  File "/bigdata/src/musicbrainz-isrcsubmit/isrcshared.py", line 182, in submit_isrcs
    self.authenticate()
  File "/bigdata/src/musicbrainz-isrcsubmit/isrcshared.py", line 153, in authenticate
    password = getpass.getpass(
AttributeError: 'function' object has no attribute 'getpass'

**Comment by SheamusPatt** [comment]
I messed up an import when refactoring - fixed in v2.2.1
